config/routes.rb
Rails.application.routes.draw do

  root to: 'talks#home'

  resources :talks
  resources :profiles
  resources :comments

  get 'follow' => 'profiles#follow'
  get 'unfollow' => 'profiles#unfollow'
  get 'like' => 'profiles#like'
  get 'unlike' => 'profiles#unlike'
  get 'talks/new'

  get 'talks/create'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  get 'tags', to: 'talks#index'
  get 'tags/:tag', to: 'talks#index', as: :tag

  get ':id', :to => "profiles#show"

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_many :talks
  has_many :comments

  extend FriendlyId
  friendly_id :nickname

  acts_as_follower
  acts_as_followable
  acts_as_liker

  validates :name, presence: true, on: :update

  validates :profile_banner,
    file_size: {
      maximum: 5.megabytes.to_i
    }

  mount_uploader :profile_banner, ProfileBannerUploader

  def self.create_with_omniauth(auth)
    create! do |profile|
      profile.provider = auth['provider']
      profile.uid = auth['uid']
      if auth['info']
        profile.nickname       = auth['info']['nickname']
        profile.name           = auth['info']['name'] || ''
        profile.location       = auth['info']['location']
        profile.description    = auth['info']['description']
        profile.image          = auth['info']['image']

        profile.website_url    = auth['info']['urls']['Website']
        profile.twitter_url    = auth['info']['urls']['Twitter']
        profile.profile_background_image_url = auth['extra']['raw_info']['profile_background_image_url']
        profile.profile_background_image_url_https = auth['extra']['raw_info']['profile_background_image_url_https']
      end
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_profile!, except: [:show, :index]
  before_action :correct_user?, :only => :edit
  before_action :set_profile, only: [:show, :edit, :update]
  before_action :set_darker_background, only: [:edit, :update]
  def index
    @profiles = Profile.all
    redirect_to root_url
  end

  def show
    @profileTalks = @profile.talks.order('created_at DESC').all
    @followers = @profile.followers(Profile)
    @following = @profile.followees(Profile)
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to profile_url(@profile), notice: t('profile_successfully_updated')
    else
      render 'edit'
    end
  end

  def follow
    @profile = Profile.friendly.find(params[:profile])
    current_user.toggle_follow!(@profile)
  end

  def unfollow
    @profile = Profile.friendly.find(params[:profile])
    current_user.unfollow!(@profile)
  end

  def like
    @likeable = Talk.find(params[:likeable_id])
    current_user.like!(@likeable)
  end

  def unlike
    @likeable = Talk.find(params[:likeable_id])
    current_user.unlike!(@likeable)
  end

  private

  def profile_params
    params.require(:profile).permit(:name, :profile_banner, :description)
  end

  def set_profile
    @profile = Profile.friendly.find(params[:id])
  end
end

app/views/profiles/_followers.html.erb
<%= link_to '', :'data-toggle' => 'modal', :'data-target' => '.followers-modal', title: '#{@profile.followers(Profile).count} Followers' do %>
<strong class='block'><%= @profile.followers(Profile).count %></strong>
<small>Followers</small>
<% end %>

<div class='modal fade followers-modal text-left' tabindex='-1' role='dialog' aria-labelledby='mySmallModalLabel' aria-hidden='true'>
  <div class='modal-dialog modal-sm'>
    <div class='modal-content'>

      <button type='button' class='close' data-dismiss='modal'>
        <span aria-hidden='true'>&times;</span>
        <span class='sr-only hide'>Close</span>
      </button>

      <div class='modal-body'>
        <h3 class='margin-bottom-two margin-top-none'><%= pluralize(@followers.length, 'Follower') %></h3>

        <% @followers.each do |profile|%>

        <div class='margin-bottom-one ell'>
          <%= link_to profile_url(profile), :class=> 'block flag' do %>
          <div class='flag__image'>
            <img src='<%= profile.image %>' alt='<%= profile.name %>' style='width:64px;height:64px;'>
          </div>
          <h4 class='margin-bottom-none flag__image'>
            <%= profile.name %>
          </h4>
          <% end %>
        </div>

        <% end %>

      </div>

    </div>
  </div>
</div>

app/views/profiles/_following.html.erb
<%= link_to '', :'data-toggle' => 'modal', :'data-target' => '.following-modal', title: "#{@profile.followees(Profile).count} Following" do %>
<strong class='block'><%= @profile.followees(Profile).count %></strong>
<small>Following</small>
<% end %>

<div class='modal fade following-modal text-left' tabindex='-1' role='dialog' aria-labelledby='mySmallModalLabel' aria-hidden='true'>
  <div class='modal-dialog modal-sm'>
    <div class='modal-content'>

      <button type='button' class='close' data-dismiss='modal'>
        <span aria-hidden='true'>&times;</span>
        <span class='sr-only hide'>Close</span>
      </button>

      <div class='modal-body'>
        <h3 class='margin-bottom-two margin-top-none'><%= pluralize(@following.length, 'Following') %></h3>

        <% @following.each do |profile|%>

        <div class='margin-bottom-one ell'>
          <%= link_to profile_url(profile), :class=> 'block flag' do %>
          <div class='flag__image'>
            <img src='<%= profile.image %>' alt='<%= profile.name %>' style='width:64px;height:64px;'>
          </div>
          <h4 class='margin-bottom-none flag__image'>
            <%= profile.name %>
          </h4>
          <% end %>
        </div>

        <% end %>

      </div>

    </div>
  </div>
</div>

app/views/profiles/_profile.html.erb
<div class='column large-2 small-4 margin-bottom-two'>
  <%= link_to profile.nickname, class: 'block dark-gray', title: 'Profile' do %>
  <div class='media-cover flex-embed flex-embed--16by9 margin-bottom-half gray-bg relative' style='background-image: url(<%= profile.image if profile.image %>)'>
  </div>
  <div class='card-inside gray-bg padding-half text-center'>
    <%= profile.name %>
  </div>
  <% end %>
</div>

app/views/profiles/edit.html.erb
<% content_for :title do %>
Edit Profile
<% end %>

<div class='margin-top-two'>
  <%= form_for :profile, url: profile_path(@profile), html: { multipart: true }, method: :patch do |f| %>
  <div class='row'>

    <div class='medium-8 large-6 column column--center'>

      <div class='form-group'>
        <%= f.label :profile_banner, :class => 'hide'%>
        <div class='row'>
          <div class='medium-6 large-8 column hide'>
            <%= f.file_field :profile_banner, class: 'form-control margin-bottom-none' %>
            <small class='dark-gray'>Recommended dimensions of 1500×500</small>
          </div>
          <label for='profile_profile_banner'>
            <div class='medium-12 large-12 column'>
              <% if @profile.profile_banner.present? %>
              <div class='flex-embed flex-embed--3by1 white-bg media-cover pointer on-hover'style='background-image: url(<%= @profile.profile_banner_url if @profile.profile_banner.present? %>)' title='Change your profile header'>
                <div class='overlay-on-hover absolute pin-all'>
                  <div class='on-hover-inner center'>
                    <h2 class='white ion-camera margin-none text-center'></h2>
                    <p class='white'>Maximum file size of 2MB</p>
                  </div>
                </div>
              </div>
              <% else %>
              <div class='padding-top-four white-bg border-bottom padding-bottom-four text-center pointer bold' title='Click to change Profile Header'>
                <h2 class='dark-gray inline ion-camera margin-none'></h2>
                <p class='dark-gray'>Maximum file size of 2MB</p>
              </div>
              <% end %>
            </div>
          </label>
        </div>
      </div>

      <div class='white-bg padding-two'>

        <div class='row'>

          <div class='large-12 column'>

            <h3 class='text-center margin-top-none margin-bottom-one hide'>Profile</h3>

            <% if @profile.errors.any? %>
            <ul class='list-bare'>
              <% @profile.errors.full_messages.each do |msg| %>
              <li class='margin-bottom-one danger'><%= msg %></li>
              <% end %>
            </ul>
            <% end %>

            <div class='form-group'>
            <%= f.label :name, class: 'hide'%>
              <%= f.text_field :name, type: 'text', autofocus: true, placeholder: 'Name', class: 'form-control',required: 'true' %>
            </div>

            <div class='form-group relative'>
              <%= f.label :description, class: 'hide'%>
              <%= f.text_area :description, class: 'form-control profile-bio', placeholder: 'Your Bio', maxlength: '140' %>
              <span class='profile-bio-count absolute pin-top-right small padding-right-quarter dark-gray'></span>
            </div>

            <%= f.submit 'Update Profile',  class:'button button-primary'%>

          </div>

        </div>
      </div>
    </div>

  </div>
  <% end %>
</div>

app/views/profiles/follow.js.erb
$('.profile-<%= @profile.id %> > #follow_form').html("<%= escape_javascript(render 'shared/unfollow', profile: @profile) %>")

app/views/profiles/index.html.erb
<% content_for :title do %>
Profiles
<% end %>

<div class='row'>
  <div class='large-12 column'>
   <h3>Profiles</h3>
 </div>

 <% @profiles.each do |profile| %>
 <%= render profile %>
 <% end %>

</div>

app/views/profiles/like.js.erb
$('#like_form').html("<%= escape_javascript(render 'shared/unlike', likeable: @likeable) %>")
$('.likes').html("<%= pluralize(@likeable.likers(Profile).count, '')%>")

app/views/profiles/show.html.erb
<% content_for :title do %>
<%= @profile.name %>
<% end %>

<% content_for :description do %>
<%= truncate @profile.description, length: 155 %>
<% end %>

<% content_for :graph_image do %>
<%= @profile.image if @profile.image %>
<% end %>

<div class='dark-bg relative media-cover' style='background-image: url(<%= @profile.profile_banner_url if @profile.profile_banner.present? %>)'>
  <div class='card__overlay'></div>
  <div class='row'>
    <div class='large-10 column column--center'>
      <div class='flex-embed flex-embed--16by9'>
      </div>
    </div>
  </div><!-- row -->

  <% if user_signed_in? and current_user == @profile and not @profile.profile_banner.present? %>
  <%= link_to edit_profile_path(current_user), :class=> 'absolute pin-bottom-right padding-one white' do %>
  <small class='border-all padding-right-one padding-left-one padding-top-half padding-bottom-half inline-block'>
    <span class='ion-plus margin-right-half'></span>
    Add a header photo
  </small>
  <% end %>
  <% end %>
</div><!-- media-cover -->

<div class='gray-bg'>
  <div class='row margin-bottom-two'>
   <div class='large-10 column column--center'>

     <div class='row'>

      <div class='small-12 medium-6 large-8 column'>

        <div class='row'>
          <div class='small-4 large-3 column'>
            <img src='<%= @profile.image if @profile.image %>' class='block'>
          </div>

          <div class='small-8 large-9 column'>
            <h3 class='margin-bottom-one margin-top-one'>
              <%= @profile.name if @profile.name %>
              <small>
                <a href='<%= @profile.twitter_url %>' target='_blank' class='ion-social-twitter notice'></a>
              </small>
            </h3>
            <p class='margin-none'><%= @profile.description if @profile.description %></p>
          </div>
        </div>

      </div>

      <div class='small-12 medium-6 large-4 column padding-top-three padding-bottom-two'>

        <div class='small-3 large-3 column text-center'>
          <strong class='block'><%= @profile.talks.count %></strong>
          <small><%= 'Talk'.pluralize(@profile.talks.count)%></small>
        </div>

        <div class='small-3 large-3 column text-center'>
          <%= render 'followers' %>
        </div>

        <div class='small-3 large-3 column text-center'>
          <%= render 'following' %>
        </div>

        <div class='small-3 large-3 column'>
          <div class='text-center'>
            <%= render 'shared/follow_form' , profile: @profile %>
          </div>
        </div>

      </div>

    </div><!-- row -->

  </div>
</div>
</div><!-- gray-bg -->


<div class='row'>
  <div class='large-10 column column--center'>
    <div class='row'>

      <% if @profileTalks.length == 0 %>
      <%= render 'shared/talk_card_placeholders' %>
      <% end %>

      <% if @profileTalks.length == 0 and user_signed_in? and current_user == @profile %>
      <div class='large-12 column'>
        <div class='margin-top-two margin-bottom-four text-center'>
          <%= link_to({:action => 'new', :controller => 'talks'}, {:class => 'button button-primary'}) do %>
          <span class='ion-plus margin-right-one'></span> Add Your First Talk
          <% end %>
        </div>
      </div>
      <% end %>

      <% if @profileTalks.length > 0 %>
      <% @profileTalks.each do |talk| %>
      <%= render 'shared/talk_card', :talk => talk, hideAuthor: 'hide', classes: 'large-4 large-4 medium-6' %>
      <% end %>
      <% if user_signed_in? and current_user == @profile %>
      <%= render 'shared/talk_card_add_placeholder' %>
      <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/profiles/unfollow.js.erb
$('.profile-<%= @profile.id %> > #follow_form').html("<%= escape_javascript(render 'shared/follow', profile: @profile) %>")

app/views/profiles/unlike.js.erb
$('#like_form').html("<%= escape_javascript(render 'shared/like', likeable: @likeable) %>")
$('.likes').html("<%= pluralize(@likeable.likers(Profile).count, '')%>")