config/routes.rb
Rails.application.routes.draw do

  root to: 'talks#home'

  resources :talks
  resources :profiles
  resources :comments

  get 'follow' => 'profiles#follow'
  get 'unfollow' => 'profiles#unfollow'
  get 'like' => 'profiles#like'
  get 'unlike' => 'profiles#unlike'
  get 'talks/new'

  get 'talks/create'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  get 'tags', to: 'talks#index'
  get 'tags/:tag', to: 'talks#index', as: :tag

  get ':id', :to => "profiles#show"

end

app/models/talk.rb
require 'acts-as-taggable-on'

class Talk < ActiveRecord::Base
  include PublicActivity::Common

  belongs_to :profile
  has_many :comments
  acts_as_taggable
  acts_as_likeable
  paginates_per 25

  validates :url, :tag_list, presence: true, on: :create
  validates :title, :tag_list, presence: true, on: :update
  validates :url, uniqueness: { message: 'is already used before.' }, on: :create
  is_impressionable counter_cache: true, column_name: :view_count, unique: :all

  def self.search(query)
    where("title like ?", "%#{query}%")
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController

  require 'net/http'
  require 'json'
  require 'cgi'

  before_action :authenticate_profile!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_darker_background, only: [:new, :create, :edit]
  impressionist actions: [:show], unique: [:session_hash]

  def home
    @talks = Talk.order('created_at DESC').all.page params[:page]
    @featured = Talk.order('view_count DESC').limit(3)
    if user_signed_in?
      followees_ids = current_user.followees(Profile)
      @activities = PublicActivity::Activity.where(owner_id: followees_ids, owner_type: 'Profile').order('created_at DESC')
    end
  end

  def index
    if params[:search]
      @talks = Talk.tagged_with(params[:search]).order('created_at DESC') \
             | Talk.search(params[:search]).order('created_at DESC')
    elsif params[:tag]
      @talks = Talk.tagged_with(params[:tag]).order('created_at DESC').page params[:page]
    else
      @talks = Talk.all.page params[:page]
    end
  end

  def new
    @talk = Talk.new
  end

  def to_param
    profilename
  end

  def create
    url_encoded = CGI.escape(params[:talk][:url])
    req_url = URI.parse('http://api.embed.ly/1/oembed?key=' + ENV['EMBEDLY_API_KEY'] + '&url=' + url_encoded)
    req = Net::HTTP::Get.new(req_url.to_s)
    res = Net::HTTP.start(req_url.host, req_url.port) {|http|
        http.request(req)
    }

    @json  = JSON.parse(res.body)

    @talk = Talk.new(talk_params)

    @talk.url              = params[:talk][:url].to_s
    @talk.url_type         = @json['type']

    if @talk.url_type != 'video'
      flash[:danger] = t('video_url_is_not_supported')
      redirect_to(:action => 'new')
    end

    @talk.version          = @json['version']
    @talk.provider_url     = @json['provider_url']
    @talk.provider_name    = @json['provider_name']

    @talk.title            = @json['title']
    @talk.html             = @json['html']
    @talk.description      = @json['description']

    @talk.author_name      = @json['author_name']
    @talk.author_url       = @json['author_url']

    @talk.width            = @json['width']
    @talk.height           = @json['height']

    @talk.thumbnail_url    = @json['thumbnail_url']
    @talk.thumbnail_width  = @json['thumbnail_width']
    @talk.thumbnail_height = @json['thumbnail_height']

    @talk.profile_id = current_user.id

    if @talk.save
      @talk.create_activity :create, owner: current_user
      flash[:notice] = t('video_successfully_published')
      redirect_to @talk
    else
      render 'new'
    end
  end

  def show
    @talk    = Talk.find(params[:id])
    @likeable = @talk
    @likers   = @talk.likers(Profile)
    @comment = Comment.new
    @comments = @talk.comments
  end

  def edit
    @profile = Talk.find(params[:id]).profile
    @talk = Talk.find(params[:id])
    unless current_user == @profile
      redirect_to root_url, alert: t('access_denied')
    end
  end

  def update
    @talk = Talk.find(params[:id])

    if @talk.update(update_params)
      redirect_to @talk, notice: t('video_successfully_updated')
    else
      render 'edit'
    end
  end

  def destroy
    @talk = Talk.find(params[:id])
    @talk.destroy

    redirect_to '/'
  end

  private
  def talk_params
    params.require(:talk).permit(:url, :tag_list)
  end

  def update_params
    params.require(:talk).permit(:title, :description, :tag_list)
  end
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/talks/edit.html.erb
<% content_for :title do %>
Edit - <%= @talk.title %>
<% end %>

<div class='margin-top-two margin-bottom-two'>

  <div class='row'>

    <div class='medium-10 large-8 column column--center'>
      <div class='white-bg padding-two'>

        <h3 class='text-center margin-top-none margin-bottom-one'>Edit</h3>

        <% if @talk.errors.any? %>
        <ul class='list-bare'>
          <% @talk.errors.full_messages.each do |msg| %>
          <li class='margin-bottom-one danger'><%= msg %></li>
          <% end %>
        </ul>
        <% end %>

        <div class='row'>
          <div class='large-12 column'>
            <%= form_for :talk, url: talk_path(@talk), method: :patch do |f| %>

            <div class='form-group'>
              <%= f.label :title, :class=> 'hide' %>
              <%= f.text_field :title, type: 'text', placeholder: 'Title', class: 'form-control', required: 'true' %>
            </div>

            <div class='form-group'>
              <%= f.label :tag_list, class: 'hide' %>
              <%= f.text_field :tag_list, type: 'text', placeholder: 'Tags', class: 'form-control', required: 'true' %>
            </div>

            <div class='form-group'>
              <%= f.label :description, class: 'hide' %>
              <%= f.text_area :description, autofocus: true, placeholder: 'Description', class: 'form-control margin-bottom-none', hatch: true %>
            </div>

            <div class='margin-bottom-one text-right'>
              <small class='dark-gray'>Markdown and syntax highlight are supported.</small>
            </div>

            <div class='form-group'>
              <%= f.submit 'Update', class:'button button-primary'%>
              <%= link_to 'Delete', talk_path(@talk), method: :delete, data: { confirm: 'Are you sure you want to delete this video?' }, class: 'button button-small right' %>
            </div>

            <% end %>
          </div>
        </div>

      </div>
    </div>

  </div>

</div>

app/views/talks/home.html.haml
- unless user_signed_in?
  = render 'shared/hero'

.row
  .large-12.column
    - if user_signed_in? and @activities.length > 0
      %h5.margin-top-one.margin-bottom-one
        Feed -
        %span.dark-gray People you follow
      .row
        - @activities.each do |activity|
          = render_activity activity
      .border-bottom

.row.hide
  .large-12.column
    %h5 Featured

.margin-top-one.padding-bottom-one.hide
  .row
    - @featured.each do |talk|
      = render 'shared/talk_card', talk: talk, classes: 'large-4'

.row
  .large-12.column
    %h5{ class: 'margin-bottom-one margin-top-one' } Latest

.row
  - @talks.each do |talk|
    = render 'shared/talk_card', talk: talk, classes: 'large-4 medium-6'

= render 'shared/pagination'

app/views/talks/index.html.erb
<% content_for :title do %>
Videos
<% end %>

<div class='margin-top-one'>
  <div class='row '>

    <div class='large-2 column'>
      <ul class='list-bare'>
        <% tag_cloud Talk.tag_counts, %w{s m l} do |tag| %>
        <li>
          <%= link_to tag_path(tag.name), class: 'small border-bottom padding-top-half padding-bottom-half block dark-gray' do %>
          <%= tag.name %>
          <span class='right'><%= tag.count %></span>
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>

    <div class='large-10 column'>
      <div class='row'>

        <% if params[:search] %>
        <div class='large-12 column'>
          <h3 class='margin-top-none margin-bottom-one regular'>We found <%= pluralize(@talks.length, 'video') %> about <span><%= params[:search] %></span></h3>
        </div>
        <% end %>

        <% if params[:tag] %>
        <div class='large-12 column'>
          <h3 class='margin-top-none margin-bottom-one regular'><%= params[:tag] %></span></h3>
        </div>
        <% end %>

        <% @talks.each do |talk| %>
        <%= render 'shared/talk_card', talk: talk, classes: 'large-4' %>
        <% end %>
      </div>
      <% unless params[:search] %>
      <%= render 'shared/pagination' %>
      <% end %>
    </div>

  </div>
</div>

app/views/talks/new.html.erb
<% content_for :title do %>
New Talk
<% end %>

<div class='margin-top-two'>

  <%= form_for @talk, url: talks_path do |f| %>

  <div class='row'>

  <div class='medium-8 large-6 column column--center'>
  <div class='white-bg padding-two'>

    <h3 class='text-center margin-top-none margin-bottom-one'>New</h3>

        <% if @talk.errors.any? %>
        <ul class='list-bare'>
          <% @talk.errors.full_messages.each do |msg| %>
          <li class='margin-bottom-one danger'><%= msg %></li>
          <% end %>
        </ul>
        <% end %>

        <div class='row'>
        <div class='large-12 column'>
        <div class='form-group'>
              <%= f.text_field :url, type: 'url', placeholder: 'URL (Youtube , Vimeo)', class: 'form-control', required: 'true' %>
            </div>
          </div>

          <div class='large-12 column'>
          <div class='form-group'>
              <%= f.text_field :tag_list, type: 'text', placeholder: 'Tags', class: 'form-control', required: 'true' %>
            </div>
          </div>

          <div class='large-8 column'>
            <%= f.submit 'Add', class: 'button button-primary' %>
          </div>
        </div>

      </div><!-- white-bg padding-two -->
    </div><!-- large-6 -->

  </div>
  <% end %>
</div>

app/views/talks/show.html.erb
<% content_for :title do %>
<%= truncate @talk.title, length: 60 %>
<% end %>

<% content_for :description do %>
<%= truncate @talk.description, length: 155 %>
<% end %>

<% content_for :graph_image do %>
<%= @talk.thumbnail_url if @talk.thumbnail_url %>
<% end %>

<div class='dark-bg'>
  <div class='row'>
    <div class='large-10 column column--center'>
      <div class='flex-embed flex-embed--16by9'>
        <% if @talk.html %>
        <%= @talk.html.html_safe %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class='row'>
  <div class='large-10 column column--center margin-bottom-two'>

    <div class='row'>
      <div class='large-9 column'>
        <h3 class='margin-top-two'><%= @talk.title %></h3>
        <div class='border-bottom margin-bottom-one padding-bottom-one'>
          <%= markdown(@talk.description) %>
        </div>

        <div class='margin-bottom-one'>
          <h3>Comments <span class='dark-gray'><small class='comments-count'><%= @talk.comments.count %></small></span></h3>
          <%= render 'comments/comment_form' %>
        </div>

        <% if @talk.profile == current_user %>
        <%= link_to edit_talk_path(@talk), :title => 'Edit', :class => 'dark-gray' do %>
        <p class='border-all padding-one block'>
          <span class='ion-information dark-gray margin-right-half'></span>
          <small>
            You can edit the video description, markdown and syntax highlight are supported.
          </small>
        </p>
        <% end %>
        <% end %>
      </div>

      <div class='large-3 column'>

        <div class='margin-bottom-one padding-top-two padding-bottom-one border-bottom'>

          <div class='row'>
            <div class='large-12 medium-6 small-12 column text-left'>

              <!-- Talk Like & views & Share -->
              <div class='margin-bottom-one padding-bottom-one border-bottom clearfix'>

                <!-- Like Button -->
                <% if user_signed_in? %>
                <%= render 'shared/like_form', likeable: @talk %>
                <% else %>

                <%= link_to '', :class=> 'button button-icon left', :'data-toggle'=>'modal', :'data-target'=>'.login-modal', :title => 'Like' do %>
                <span class='ion-android-favorite-outline'></span>
                <% end %>

                <%= render 'shared/login_modal' %>

                <% end %>

                <span class='likes padding-top-quarter padding-bottom-quarter padding-right-one padding-left-one white-bg border-right border-top border-bottom left small'>
                  <% if @talk.likers(Profile).count > 0 %>
                  <%= link_to '', :class=> '', :'data-toggle' => 'modal', :'data-target' => '.likers-modal', :title => 'Likers' do %>
                  <%= pluralize(@talk.likers(Profile).count, '')%>
                  <% end %>
                  <%= render 'shared/likers_modal', :likers => @likers %>
                  <% else %>
                  <%= pluralize(@talk.likers(Profile).count, '')%>
                  <% end %>
                </span>

                <!-- End Like Button -->

                <!-- Views Count -->
                <span class='padding-top-quarter padding-bottom-quarter padding-right-one padding-left-one white-bg border-all small margin-left-half left ion-eye dark-gray'>
                  <span class='padding-left-quarter'><%= @talk.impressionist_count %></span>
                </span>
                <!-- / Views Count -->

                <!-- Share Button -->
                <span class='padding-top-quarter padding-bottom-quarter padding-right-one padding-left-one white-bg border-all small margin-left-half right'>
                  <a href='http://twitter.com/share?url=<%= request.original_url %>&amp;text=<%= @talk.title %>' class='' title='Share on Twitter' target='_blank'>
                    <span class='notice ion-social-twitter'></span>
                  </a>
                </span>

                <!-- / Share Button -->
              </div>
              <!-- Talk Like & views & Share -->

              <!-- Talk Author block -->
              <div class='margin-bottom-one padding-bottom-one border-bottom ell'>
                <%= link_to profile_url(@talk.profile), :class=> 'block gray-bg flag' do %>
                <div class='flag__image'>
                  <img src='<%= @talk.profile.image %>' alt='<%= @talk.profile.name %>' style='width:64px;height:64px;'>
                </div>
                <h4 class='margin-bottom-none flag__image'>
                  <%= @talk.profile.name %>
                </h4>
                <% end %>
              </div>
              <!-- / Talk Author block -->

            </div>
          </div>

          <div class='margin-top-one padding-top-one border-top clearfix'>
            <% if !@talk.tag_list.empty? %>
            <h4 class='margin-bottom-one margin-top-none'>Tags</h4>
            <%= raw @talk.tag_list.map { |t| link_to t, tag_path(t), class: 'tag radius' }.join('  ') %>
            <% end %>
          </div>

        </div>

        <!-- Talk Edit Button -->
        <% if @talk.profile == current_user %>
        <%= link_to edit_talk_path(@talk), :class=> 'button button-icon', :title => 'Edit' do %>
        <span class='ion-edit'></span>
        <% end %>
        <% end %>
        <!-- / Talk Edit Button -->

      </div>

    </div>
  </div>
</div>


<!-- related talks by the current talk tags -->
<% if Talk.tagged_with([@talk.tag_list]).length  > 1 %>
<div class='gray-bg padding-top-two padding-bottom-one'>
  <div class='row'>
    <div class='large-10 column column--center'>
      <h3>Related Talks</h3>
    </div>

    <div class='large-10 column column--center'>
      <div class='row'>
        <% Talk.tagged_with([@talk.tag_list]).each do |talk| %>
        <% if talk.id != @talk.id %>
        <%= render 'shared/talk_card', talk: talk, classes: 'large-4' %>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>