config/routes.rb
Rails.application.routes.draw do

  root to: 'talks#home'

  resources :talks
  resources :profiles
  resources :comments

  get 'follow' => 'profiles#follow'
  get 'unfollow' => 'profiles#unfollow'
  get 'like' => 'profiles#like'
  get 'unlike' => 'profiles#unlike'
  get 'talks/new'

  get 'talks/create'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  get 'tags', to: 'talks#index'
  get 'tags/:tag', to: 'talks#index', as: :tag

  get ':id', :to => "profiles#show"

end

app/views/shared/_comment_form.html.erb
<%= link_to pluralize(@comments.count, 'comment'), @talk %>

<div id="comments-list">
<% @comments.each do |comment| %>

<%= render 'comments/comment', :comment => comment %>

<% end %>
</div>


<%= form_for(@comment, remote: true) do |f| %>
<%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
<% if @comment.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this talk from being saved:</h2>
  <ul>
    <% @comment.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= f.hidden_field :talk_id, value: @talk.id %>

<div class="field">
  <%= f.text_area :content, :class => 'form-control', :required => 'true', :placeholder => 'Comment' %>
</div>
<div class="actions">
  <%= f.submit class: 'button button-primary' %>
</div>
<% end %>

app/views/shared/_follow.html.erb
<%= link_to follow_path(profile: @profile.id), remote: true, method: 'get', class: 'button button-icon button-primary', title: 'Follow' do %>
<span class='ion-plus' title='Follow'></span>
<% end %>

app/views/shared/_head.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
  <title><%= content_for?(:title) ? yield(:title) : t('app_name') %></title>
  <meta name='description' content="<%= content_for?(:description) ? yield(:description) : t('app_descroption') %>">

  <%= render 'shared/open_graph' %>

  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css">

  <%= stylesheet_link_tag 'application', media: 'all' %>

  <%= javascript_include_tag 'application' %>

  <link rel='shortcut icon' href='/favicon.ico'>

  <%= csrf_meta_tags %>
</head>
<body class='<%= body_class %>'>

app/views/shared/_header.html.erb
<header role='banner' class='white-bg'>
  <%= render 'layouts/navigation' %>
</header>

app/views/shared/_hero.html.erb
<div class='hero white padding-top-four padding-bottom-four relative'>
  <div class='overlay'></div>
  <div class='row'>
    <div class='large-12 column text-center'>
      <h1>Your space to share your creative Talk.</h1>
      <h4>Ontwik makes it easy to share and find the best and latest talks, interviews for Developers & Designers and Creatives. </h4>
      <%= link_to 'Connect with Twitter', '/signin', class: 'button button-info button-twitter margin-top-one' %>
    </div>
  </div>
  <a href='http://2013.front-trends.com/' target='_blank' class='absolute pin-bottom-right padding-one dark-gray'><small>Image</small></a>
</div>

app/views/shared/_like.html.erb
<%= link_to like_path(likeable_id: likeable.id, likeable_type: likeable.class) , remote: true, method: :get, class: 'button button-icon', title: 'Like' do %>
<span class='ion-android-favorite-outline'></span>
<% end %>

app/views/shared/_likers_modal.html.erb
<div class='modal fade likers-modal' tabindex='-1' role='dialog' aria-labelledby='mySmallModalLabel' aria-hidden='true'>
  <div class='modal-dialog modal-sm'>
    <div class='modal-content'>

      <button type='button' class='close' data-dismiss='modal'>
        <span aria-hidden='true'>&times;</span>
        <span class='sr-only hide'>Close</span>
      </button>

      <div class='modal-body'>
        <h3 class='margin-bottom-two margin-top-none'>Liked by <%= pluralize(@likers.length, 'people') %></h3>

        <% @likers.each do |profile|%>

        <div class='margin-bottom-one ell'>
        <%= link_to profile_url(profile), :class=> 'block flag' do %>
          <div class='flag__image'>
            <img src='<%= profile.image %>' alt='<%= profile.name %>' style='width:64px;height:64px;'>
          </div>
          <h4 class='margin-bottom-none flag__image'>
            <%= profile.name %>
          </h4>
          <% end %>
        </div>

        <% end %>

      </div>

    </div>
  </div>
</div>

app/views/shared/_login_modal.html.erb
<div class='modal fade login-modal' tabindex='-1' role='dialog' aria-labelledby='mySmallModalLabel' aria-hidden='true'>
  <div class='modal-dialog'>
    <div class='modal-content'>

      <button type='button' class='close' data-dismiss='modal'>
        <span aria-hidden='true'>&times;</span>
        <span class='sr-only hide'>Close</span>
      </button>

      <div class='modal-body text-center'>
        <h3 class='margin-bottom-three'>Join to Follow, Like and Add Talks </h3>
        <%= link_to 'Connect with Twitter', '/signin', class: 'button button-info button-twitter' %>
      </div>

    </div>
  </div>
</div>

app/views/shared/_open_graph.html.haml
/ Twitter Card data

%meta{name: 'twitter:card', content: 'summary'}
%meta{name: 'twitter:site', content: '@ontwiik'}
%meta{name: 'twitter:url', content: request.original_url}
%meta{name: 'twitter:title', content: content_for?(:title) ? yield(:title) : t('app_name')}
%meta{name: 'twitter:description', content: content_for?(:description) ? yield(:description) : t('tagline')}

- if content_for?(:graph_image)
  %meta{name: 'twitter:image', content: yield(:graph_image)}

/ Open Graph data
%meta{content: content_for?(:title) ? yield(:title) : t('app_name'), property: 'og:title'}
%meta{content: "article", property: 'og:type'}
%meta{content: request.original_url, property: 'og:url'}
%meta{content: content_for?(:description) ? yield(:description) : t('tagline'), property: 'og:description'}
%meta{content: t('app_name'), property: 'og:site_name'}

- if content_for?(:graph_image)
  %meta{content: yield(:graph_image), property: 'og:image'}

app/views/shared/_pagination.html.erb
<div class='row'>
  <div class="large-12 column">
    <%= paginate @talks %>
  </div>
</div>

app/views/shared/_talk_card.html.erb
<div class='column <%= classes %> margin-bottom-two'>
  <div class='card'>
    <%= link_to talk, class: 'ell block uppercase' do %>
    <div class='media-cover flex-embed flex-embed--16by9' style='background-image: url(<%= talk.thumbnail_url %>)'>

      <div class='overlay absolute pin-all'></div>

      <div class='absolute pin-bottom padding-one'>
        <small class='<%= hideAuthor if defined?(hideAuthor) %>'>
          <%= link_to profile_url(talk.profile), title: talk.profile.name, class: 'ell block white' do %>
          <%= talk.profile.name %>
          <% end %>
        </small>
        <h3 class='card-title'>
          <%= link_to talk, class: 'ell block white', title: talk.title do %>
          <%= talk.title %>
          <% end %>
        </h3>
      </div>

    </div>
    <% end %>
  </div>
</div>

app/views/shared/_unfollow.html.erb
<%= link_to unfollow_path(profile: @profile.id), remote: true, method: 'get', class: 'button button-icon button-alert', title: 'unfollow' do %>
<span class='ion-close' title='unfollow'></span>
<% end %>

app/views/shared/_unlike.html.erb
<%= link_to unlike_path(likeable_id: likeable.id, likeable_type: likeable.class ), remote: true, method: :get, class: 'button button-icon', title: 'Unlike' do %>
<span class='ion-android-favorite-outline danger'></span>
<% end %>

app/views/shared/_video_card_add_placeholder.html.erb
<div class="column large-4 margin-bottom-two">
  <%= link_to({:action => 'new', :controller => 'videos'}, {:class => "dark-gray"}) do %>
  <div class="media-cover flex-embed flex-embed--16by9 margin-bottom-half gray-bg relative">
    <div class="center text-center">
      <span class="iconicstroke-plus"></span>
      <h4 class="margin-none">New</h4>
    </div>
  </div>
  <div class="card-inside gray-bg padding-half">
  </div>
  <% end %>
</div>