config/routes.rb
Rails.application.routes.draw do

  root to: 'talks#home'

  resources :talks
  resources :profiles
  resources :comments

  get 'follow' => 'profiles#follow'
  get 'unfollow' => 'profiles#unfollow'
  get 'like' => 'profiles#like'
  get 'unlike' => 'profiles#unlike'
  get 'talks/new'

  get 'talks/create'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  get 'tags', to: 'talks#index'
  get 'tags/:tag', to: 'talks#index', as: :tag

  get ':id', :to => "profiles#show"

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
<div class='padding-one white alert <%= name.to_s == 'notice' ? 'success' : 'danger' %>-bg'>
  <div class='row'>
    <div class='large-12 column'>
      <button type='button' class='close close--alert right white' data-dismiss='alert' aria-hidden='true'>&times;</button>
      <%= content_tag :div, msg, :id => 'flash_#{name}' %>
    </div>
  </div>
</div>
<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class='row'>

  <div class='small-3 medium-3 large-6 column'>
    <%= link_to image_tag('logo.png', border: 0), root_path, class: 'brand brand padding-top-half padding-bottom-half inline-block' %>
  </div>

  <div class='small-9 medium-5 large-3 column'>
    <%= form_tag talks_path, method: 'get', class: 'navbar-form navbar-left' do %>
    <div class='form-group'>
      <%= text_field_tag :search, params[:search], class: 'form-control padding-right-one padding-left-one margin-bottom-none', placeholder: 'Search', required: 'true' %>
      <button type='submit' class='ion-ios-search-strong btn-search absolute white-bg dark-gray'></button>
    </div>
    <% end %>
  </div>

  <div class='small-12 medium-4 large-3 column text-right'>
    <ul class='nav list-bare'>
      <%= render 'layouts/profile_navigation_links' %>
    </ul>
  </div>

</div>

app/views/layouts/_profile_navigation_links.html.erb
<% if user_signed_in? %>

<li class='right'>
  <%= link_to '/signout', class: 'border-right border-left inline-block padding-right-one padding-left-one padding-top-half padding-bottom-half dark-gray', title: 'Logout' do %>
  <span class='ion-log-out'></span>
  <% end %>
</li>

<li class='right'>
  <%= link_to edit_profile_path(current_user), class: 'border-left block padding-right-one padding-left-one padding-top-half padding-bottom-half dark-gray', title: 'Profile Settings' do %>
  <span class='ion-gear-a'></span>
  <% end %>
</li>

<li class='right'>
  <%= link_to profile_url(current_user), class: 'block padding-right-one padding-left-one padding-top-half padding-bottom-half dark-gray', title: 'Profile' do %>
  <span class='ion-person'></span>
  <% end %>
</li>

<li class='right'>
  <%= link_to({action: 'new', controller: 'talks'}, {class: 'border-right border-left block padding-right-one padding-left-one padding-top-half padding-bottom-half danger', title: 'Add new talk'}) do %>
  <span class='ion-plus'></span>
  <% end %>
</li>

<% else %>

<li class='right'>
  <%= link_to 'Sign in', '/signin', class: 'border-right border-left dark-gray padding-top-half inline-block block padding-right-one padding-left-one padding-top-half padding-bottom-half dark-gray' %>
</li>
<% end %>

app/views/layouts/application.html.erb
<%= render 'shared/head' %>

<%= render 'shared/header' %>

<%= render 'layouts/messages' %>

<main class='main'>
  <%= yield %>
</main>

<%= render 'shared/footer' %>

app/views/layouts/userlayout.html.erb
<%= render 'shared/head' %>

<header class='full-height media-cover relative margin-bottom-three'
style='background-image: url(<%= @profile.profile_banner_url if @profile.profile_banner.present? %>)'>

<%= render 'layouts/navigation' %>
<div class='gradient gradient--hero'></div>
<div class='container vertical-align'>
  <div class='col-sm-6 col-md-3'>
    <div class='text-center white-bg'>
      <div class='padlx padly'>

        <div class='text-center margin-bottom-one '>
          <img src='<%= @profile.image if @profile.image %>'>
          <h3><%= @profile.name if @profile.name %></h3>
          <p><%= @profile.description if @profile.description %></p>
        </div>

        <div class='row margin-bottom-one'>
          <div class='col-sm-4 col-md-4'>
            <strong class='block'><%= @profile.talks.count %></strong>
            talks
          </div>
          <div class='col-sm-4 col-md-4'>
            <strong class='block'><%= @profile.followers(Profile).count %></strong>
            Followers
          </div>
          <div class='col-sm-4 col-md-4'>
            <strong class='block'><%= @profile.followees(Profile).count %></strong>
            Following
          </div>
        </div>

        <div class='text-center'>
          <%= render 'shared/follow_form' , profile: @profile %>
        </div>

      </div>
    </div>
  </div>
</div>

</header>

<%= render 'layouts/messages' %>
<%= yield %>

<%= render 'shared/footer' %>